## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])

application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_counts = application_df['APPLICATION_TYPE'].value_counts()
app_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
app_counts.index

Index(['T3', 'T4', 'T6', 'T5', 'T19', 'T8', 'T7', 'T10', 'T9', 'T13', 'T12',
       'T2', 'T25', 'T14', 'T29', 'T15', 'T17'],
      dtype='object', name='APPLICATION_TYPE')

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9', 'T13', 'T12','T2', 'T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classif_value_counts = application_df['CLASSIFICATION'].value_counts()
classif_value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
new_classifications = classif_value_counts[classif_value_counts > 1]

new_classifications

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
classifications_to_replace = classif_value_counts[classif_value_counts < 1883].index
classifications_to_replace

Index(['C7000', 'C1700', 'C4000', 'C5000', 'C1270', 'C2700', 'C2800', 'C7100',
       'C1300', 'C1280', 'C1230', 'C1400', 'C7200', 'C2300', 'C1240', 'C8000',
       'C7120', 'C1500', 'C1800', 'C6000', 'C1250', 'C8200', 'C1238', 'C1278',
       'C1235', 'C1237', 'C7210', 'C2400', 'C1720', 'C4100', 'C1257', 'C1600',
       'C1260', 'C2710', 'C0', 'C3200', 'C1234', 'C1246', 'C1267', 'C1256',
       'C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248', 'C6100', 'C1820',
       'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245', 'C2500', 'C1570',
       'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120', 'C8210', 'C2561',
       'C4500', 'C2150'],
      dtype='object', name='CLASSIFICATION')

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classif_value_counts[classif_value_counts < 1883].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
application_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_data = pd.get_dummies(application_df)
dummies_data = dummies_data.astype(int)

dummies_data.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
X = dummies_data.drop('IS_SUCCESSFUL', axis = 1)
y = dummies_data['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_of_input_features = len(X_train_scaled[0])
hidden_nodes_layer_1 = 80
hidden_nodes_layer_2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer_1, input_dim = number_of_input_features, activation = 'relu', name = 'dense'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer_2, activation = 'relu', name = 'dense_1'))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid', name = 'dense_2'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
# Train the model
training_model = nn.fit(X_train_scaled, y_train, epochs=100, batch_size = 1)

Epoch 1/100
25724/25724 [==============================] - 83s 3ms/step - loss: 0.5607 - accuracy: 0.7279
Epoch 2/100
25724/25724 [==============================] - 83s 3ms/step - loss: 0.5584 - accuracy: 0.7305
Epoch 3/100
25724/25724 [==============================] - 83s 3ms/step - loss: 0.5564 - accuracy: 0.7289
Epoch 4/100
25724/25724 [==============================] - 83s 3ms/step - loss: 0.5542 - accuracy: 0.7315
Epoch 5/100
25724/25724 [==============================] - 83s 3ms/step - loss: 0.5538 - accuracy: 0.7298
Epoch 6/100
25724/25724 [==============================] - 83s 3ms/step - loss: 0.5515 - accuracy: 0.7323
Epoch 7/100
25724/25724 [==============================] - 85s 3ms/step - loss: 0.5528 - accuracy: 0.7309
Epoch 8/100
25724/25724 [==============================] - 83s 3ms/step - loss: 0.5530 - accuracy: 0.7331
Epoch 9/100
25724/25724 [==============================] - 84s 3ms/step - loss: 0.5519 - accuracy: 0.7312
Epoch 10/100
25724/25724 [==============================] - 85s 3ms/step - loss: 0.5523 - accuracy: 0.7317
Epoch 11/100
25724/25724 [==============================] - 85s 3ms/step - loss: 0.5528 - accuracy: 0.7304
Epoch 12/100
25724/25724 [==============================] - 84s 3ms/step - loss: 0.5532 - accuracy: 0.7334
Epoch 13/100
25724/25724 [==============================] - 84s 3ms/step - loss: 0.5514 - accuracy: 0.7318
Epoch 14/100
25724/25724 [==============================] - 84s 3ms/step - loss: 0.5509 - accuracy: 0.7315
Epoch 15/100
25724/25724 [==============================] - 85s 3ms/step - loss: 0.5509 - accuracy: 0.7283
Epoch 16/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5520 - accuracy: 0.7325
Epoch 17/100
25724/25724 [==============================] - 90s 3ms/step - loss: 0.5540 - accuracy: 0.7313
Epoch 18/100
25724/25724 [==============================] - 90s 4ms/step - loss: 0.5608 - accuracy: 0.7333
Epoch 19/100
25724/25724 [==============================] - 87s 3ms/step - loss: 0.5505 - accuracy: 0.7319
Epoch 20/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5525 - accuracy: 0.7318
Epoch 21/100
25724/25724 [==============================] - 87s 3ms/step - loss: 0.5512 - accuracy: 0.7322
Epoch 22/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5560 - accuracy: 0.7317
Epoch 23/100
25724/25724 [==============================] - 87s 3ms/step - loss: 0.5577 - accuracy: 0.7311
Epoch 24/100
25724/25724 [==============================] - 87s 3ms/step - loss: 0.5546 - accuracy: 0.7336
Epoch 25/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5522 - accuracy: 0.7322
Epoch 26/100
25724/25724 [==============================] - 87s 3ms/step - loss: 0.5538 - accuracy: 0.7311
Epoch 27/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5535 - accuracy: 0.7325
Epoch 28/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5504 - accuracy: 0.7347
Epoch 29/100
25724/25724 [==============================] - 87s 3ms/step - loss: 0.5533 - accuracy: 0.7326
Epoch 30/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5499 - accuracy: 0.7330
Epoch 31/100
25724/25724 [==============================] - 88s 3ms/step - loss: 0.5520 - accuracy: 0.7334
Epoch 32/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5503 - accuracy: 0.7331
Epoch 33/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5538 - accuracy: 0.7325
Epoch 34/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5519 - accuracy: 0.7324
Epoch 35/100
25724/25724 [==============================] - 86s 3ms/step - loss: 0.5532 - accuracy: 0.7333
Epoch 36/100
25724/25724 [==============================] - 88s 3ms/step - loss: 0.5503 - accuracy: 0.7326
Epoch 37/100
25724/25724 [==============================] - 85s 3ms/step - loss: 0.5518 - accuracy: 0.7332
Epoch 38/100
25724/25724 [==============================] - 87s 3ms/step - loss: 0.5502 - accuracy: 0.7344
Epoch 39/100
25724/25724 [==============================] - 88s 3ms/step - loss: 0.5515 - accuracy: 0.7320
Epoch 40/100
25724/25724 [==============================] - 90s 3ms/step - loss: 0.5504 - accuracy: 0.7336
Epoch 41/100
25724/25724 [==============================] - 90s 4ms/step - loss: 0.5505 - accuracy: 0.7336
Epoch 42/100
25724/25724 [==============================] - 91s 4ms/step - loss: 0.5502 - accuracy: 0.7327
Epoch 43/100
25724/25724 [==============================] - 91s 4ms/step - loss: 0.5505 - accuracy: 0.7321
Epoch 44/100
25724/25724 [==============================] - 91s 4ms/step - loss: 0.5506 - accuracy: 0.7321
Epoch 45/100
25724/25724 [==============================] - 90s 3ms/step - loss: 0.5503 - accuracy: 0.7349
Epoch 46/100
25724/25724 [==============================] - 90s 4ms/step - loss: 0.5568 - accuracy: 0.7327
Epoch 47/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5498 - accuracy: 0.7339
Epoch 48/100
25724/25724 [==============================] - 95s 4ms/step - loss: 0.5495 - accuracy: 0.7332
Epoch 49/100
25724/25724 [==============================] - 91s 4ms/step - loss: 0.5514 - accuracy: 0.7334
Epoch 50/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5510 - accuracy: 0.7346
Epoch 51/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5483 - accuracy: 0.7332
Epoch 52/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5513 - accuracy: 0.7346
Epoch 53/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5535 - accuracy: 0.7347
Epoch 54/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5510 - accuracy: 0.7344
Epoch 55/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5500 - accuracy: 0.7348
Epoch 56/100
25724/25724 [==============================] - 91s 4ms/step - loss: 0.5577 - accuracy: 0.7339
Epoch 57/100
25724/25724 [==============================] - 91s 4ms/step - loss: 0.5516 - accuracy: 0.7338
Epoch 58/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5496 - accuracy: 0.7333
Epoch 59/100
25724/25724 [==============================] - 91s 4ms/step - loss: 0.5518 - accuracy: 0.7337
Epoch 60/100
25724/25724 [==============================] - 90s 4ms/step - loss: 0.5494 - accuracy: 0.7349
Epoch 61/100
25724/25724 [==============================] - 91s 4ms/step - loss: 0.5502 - accuracy: 0.7348
Epoch 62/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5537 - accuracy: 0.7352
Epoch 63/100
25724/25724 [==============================] - 95s 4ms/step - loss: 0.5545 - accuracy: 0.7339
Epoch 64/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5537 - accuracy: 0.7352
Epoch 65/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5522 - accuracy: 0.7349
Epoch 66/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5511 - accuracy: 0.7331
Epoch 67/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5510 - accuracy: 0.7338
Epoch 68/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5514 - accuracy: 0.7346
Epoch 69/100
25724/25724 [==============================] - 91s 4ms/step - loss: 0.5522 - accuracy: 0.7352
Epoch 70/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5514 - accuracy: 0.7364
Epoch 71/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5547 - accuracy: 0.7336
Epoch 72/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5488 - accuracy: 0.7341
Epoch 73/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5596 - accuracy: 0.7345
Epoch 74/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5521 - accuracy: 0.7339
Epoch 75/100
25724/25724 [==============================] - 95s 4ms/step - loss: 0.5508 - accuracy: 0.7339
Epoch 76/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5507 - accuracy: 0.7346
Epoch 77/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5493 - accuracy: 0.7336
Epoch 78/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5487 - accuracy: 0.7341
Epoch 79/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5490 - accuracy: 0.7341
Epoch 80/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5500 - accuracy: 0.7350
Epoch 81/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5538 - accuracy: 0.7349
Epoch 82/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5515 - accuracy: 0.7354
Epoch 83/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5543 - accuracy: 0.7353
Epoch 84/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5559 - accuracy: 0.7352
Epoch 85/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5595 - accuracy: 0.7345
Epoch 86/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5499 - accuracy: 0.7355
Epoch 87/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5490 - accuracy: 0.7343
Epoch 88/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5500 - accuracy: 0.7339
Epoch 89/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5565 - accuracy: 0.7343
Epoch 90/100
25724/25724 [==============================] - 95s 4ms/step - loss: 0.5512 - accuracy: 0.7329
Epoch 91/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5510 - accuracy: 0.7339
Epoch 92/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5543 - accuracy: 0.7346
Epoch 93/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5522 - accuracy: 0.7346
Epoch 94/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5522 - accuracy: 0.7338
Epoch 95/100
25724/25724 [==============================] - 92s 4ms/step - loss: 0.5624 - accuracy: 0.7348
Epoch 96/100
25724/25724 [==============================] - 91s 4ms/step - loss: 0.5579 - accuracy: 0.7346
Epoch 97/100
25724/25724 [==============================] - 90s 4ms/step - loss: 0.5505 - accuracy: 0.7331
Epoch 98/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5551 - accuracy: 0.7339
Epoch 99/100
25724/25724 [==============================] - 94s 4ms/step - loss: 0.5515 - accuracy: 0.7339
Epoch 100/100
25724/25724 [==============================] - 93s 4ms/step - loss: 0.5567 - accuracy: 0.7338

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5823 - accuracy: 0.7263 - 614ms/epoch - 2ms/step
Loss: 0.5822717547416687, Accuracy: 0.7262973785400391

In [ ]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(